name: spark-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyspark
  - jupyterlab
  - ipykernel
  - openjdk=11
  - notebook
  - numpy
  - pandas
  - matplotlib

  - pip:
      - findspark
      - jupyter_contrib_nbextensions
      - pyspark-ai==0.1.21
